### ISSUE TITLE
7.0.2 Can't mount zfs automatically

### ISSUE THREAD

**Issue by Heavenser** [fearedbliss/bliss-initramfs#11]
I make initramfs with bliss-initramfs-7.0.2 , and then I reboot , it reminds me:
mount : mounting Gentoo/rootfs on /mnt/root failed : No such file or directory
but I can use `zpool import -R /mnt/root Gentoo ` to import the pool.

**Comment by fearedbliss** [comment]
Is Gentoo the name of your pool or the name of your root dataset? You need to bliss initramfs the name of your root dataset, it can derive the pool name from that.On Apr 8, 2017 11:53 PM, Heavens Lee <notifications@github.com> wrote:I make initramfs with bliss-initramfs-7.0.2 , and then I reboot , it reminds me:
mount : mounting Gentoo/rootfs on /mnt/root failed : No such file or directory
but I can use zpool import -R /mnt/root Gentoo to import the pool.

**Comment by Heavenser** [comment]
'Gentoo' is the name of the pool , and root dataset is 'rootfs'.
I have added kernel parameters 'root=Gentoo/rootfs' , and there is no problem in 6.8.3.

**Comment by fearedbliss** [comment]
Hey, I checked the code changes and ran some tests on some critical functions and everything seems fine. Now that you mention it, I forgot to tell you (It was part of the CHANGES/README for the 7.0.0 release), the initramfs is using a new style for how to include features in it and how to trigger the desired functionality.

Make sure to add: triggers=zfs 

to the end of your kernel command line. That should run the zfs function as before. Any other functionality would also need to be added before or after the zfs mention (depending on how you have your disks structured. Let me know if that helps.

Example:

menuentry "Gentoo - 3.9.9-FB.02" {
    insmod part_gpt
    insmod ext2

    set root=(hd0,gpt1)

    linux /vmlinuz-3.9.9-FB.02 root=tank/gentoo/root triggers=zfs quiet
    initrd /initrd-3.9.9-FB.02
}

**Comment by Heavenser** [comment]
Thank you!
