### ISSUE TITLE
Fails when /tmp is mounted "noexec"

### ISSUE THREAD

**Issue by arantius** [fearedbliss/bliss-initramfs#16]
I set things up to be paranoid, so my /tmp is mounted with options `(rw,nosuid,nodev,noexec,noatime,xattr,noacl)`.  But bliss-initramfs puts all working files inside `/tmp`, and tries to (at least) exec a copy of busybox in `/tmp` when chrooting there. Which fails for me.

A dirty patch to `temp` in `Vars` (a random directory in `os.getcwd()`, instead of in `/tmp`) makes it execute as expected.

Given that the output is indeed created in the current directory, maybe this is even a decent fix rather than just a dirty workaround?  (Possibly with a less random name, like a `bliss-initramfs-tmp-` prefix?  In case of failure to clean up.)

**Comment by fearedbliss** [comment]
Hey Arantius,

Thanks for reporting this. Your recommendation seems logical and system enough. I implemented/tested and seems fine (I haven't tested with noexec, but just using a random dir in the cwd). Seems fine. I pushed the change in the -next branch as 7.1.3. Please test it out and lmk before I tag and release to portage tree.

https://github.com/fearedbliss/bliss-initramfs/commits/next

- Jonathan

**Comment by arantius** [comment]
Checked out, switched to "next" branch, built the image successfully.

**Comment by fearedbliss** [comment]
Thanks for confirming!

**Comment by fearedbliss** [comment]
Pushed to tree. Should be publicly available in 30 min.
