### ISSUE TITLE
Rearchitect so that we can have a separate configuration file rather than modifying the hooks.

### ISSUE THREAD

**Issue by fearedbliss** [fearedbliss/bliss-initramfs#21]
It would be nice for bliss-initramfs to have one central configuration file (or maybe multiple configuration files but in /etc/bliss-initramfs) rather than having to edit the individual files. I might tackle this in the future and provide a json implementation for this since serialization/deserialization is easy, well supported, and pretty much a standard at this point.

**Comment by fearedbliss** [comment]
A centralized JSON configuration file is now included with 8.1.0 (Not released yet, will let it bake a bit - maybe 1-2 weeks or less, then I'll make a release for Gentoo ~amd64) - [Commit](https://github.com/fearedbliss/bliss-initramfs/commit/9454de7b01b821bf27e67668f769574a82f90512)

@arantius @NuLL3rr0r

**Comment by arantius** [comment]
Awesome!  I would have done it very differently, but I never did, so this is great.

FWIW I'd appreciate a `-c`/`--config` option to specify where the file is, rather than only a fixed configuration path.

**Comment by fearedbliss** [comment]
@arantius -c is a good idea. 

And yea originally I was going to replace all the hooks completely since it’s not needed in a lot of places if we bring everything from the json, but that would require a much bigger change, so instead I opted for a more adapter pattern.

**Comment by fearedbliss** [comment]
@arantius Just pushed the new argument parser rewrite.

https://github.com/fearedbliss/bliss-initramfs/commit/4f9c8bcb1aa371d150c70f9e30bdc7ffe820caa5

```
- The argument parser has been completely rewritten and is
  now using 'argparse'.

- You can now use the following arguments in the cli:

  -c, --config   - Path to the settings.json. (i.e: /home/jon/settings.json)
  -f, --features - Comma delimited list of features you want [Available: zfs, luks, basic]. (i.e: zfs,luks).
  -k, --kernel   - The name of the kernel you are building the initramfs for. (i.e: 4.14.170-FC.01)
```

**Comment by fearedbliss** [comment]
@arantius I did more testing in a few different VMs with different configs. Implemented more cleanups and features and pushed 8.1.0 out into the portage tree for ~amd64. Thanks for the feedback and help, and enjoy the release.

**Comment by NuLL3rr0r** [comment]
@fearedbliss  thank you so much for letting me know.

**Comment by fearedbliss** [comment]
@NuLL3rr0r No prob. I just pushed 9.0.0 which is a breaking change. It has full native zfs encryption support, and I've completely removed LUKS and all code related to it. If you are using LUKS+ZFS, please stay on 8.1.0 since that's the last version that will support that. If you ever move to native zfs encryption, then you are covered!

https://github.com/fearedbliss/bliss-initramfs/releases/tag/9.0.0

**Comment by NuLL3rr0r** [comment]
Thanks again. I'm native ZFS. Looking forward to it.

**Comment by arantius** [comment]
That's a shame, I'm not ready to migrate my multiple machines away from LUKS.  Maybe I'll stick with 8.1.0, maybe I'll fork.  Still, thanks for a wonderful product!

**Comment by fearedbliss** [comment]
@arantius Yup, that's the correct approach to take and what I recommend as well. The 8.X series is the last version that has LUKS while 9.X+ has native ZFS support. Breaking changes like this usually only happen in major releases which is why I decided to do it in 9.X and not 8.2.0.

This is the message I currently have for the 9.0.0 release:

```
+pkg_postinst() {
+	elog "Version 9.0.0 is a BREAKING CHANGE! bliss-initramfs now has native"
+	elog "zfs encryption support, and LUKS has been completely removed. If you"
+	elog "are using LUKS, please stay on version 8.1.0 since that is the last"
+	elog "version to support LUKS!\n"
+	elog "For a full list of changes, please read the release info located here:"
+	elog "https://github.com/fearedbliss/bliss-initramfs/releases/tag/9.0.0"
+	elog ""
+	elog "As of version 8.1.0, ${PN} has a new centralized configuration architecture."
+	elog "Any customizations you want to provide to ${PN} should be done by modifying"
+	elog "${CONFIG_FILE}. You can use the \"-c/--config\" option to provide"
+	elog "an alternate configuration path.\n"
+	elog "For a full list of changes, please read the release info located here:"
+	elog "https://github.com/fearedbliss/bliss-initramfs/releases/tag/8.1.0"
+}
```

https://gitweb.gentoo.org/repo/gentoo.git/diff/sys-kernel/bliss-initramfs/bliss-initramfs-9.0.0.ebuild?id=50ebd24d7597b1155ac2818e01641ed260467950
