### ISSUE TITLE
Can you add resume functionality?

### ISSUE THREAD

**Issue by rocky-hxh** [fearedbliss/bliss-initramfs#25]
Can you please add resume functionality?

**Comment by rocky-hxh** [comment]
> Can you please add resume functionality?

If not, I want to know why, thanks very much.

**Comment by rocky-hxh** [comment]
`diff --git a/files/init b/files/init
index 6751fc1..d682a7a 100755
--- a/files/init
+++ b/files/init
@@ -26,6 +26,7 @@ _use_addon=0
 
 _new_root="/mnt/root"
 _init="/sbin/init"
+_resume="dev/mapper/swap"
 _key_drive="/mnt/key"
 _embedded_keyfile="/etc/keyfile"
 _cache_file="/etc/zfs/zpool.cache"
@@ -139,6 +140,9 @@ ParseKernelParameters()
         root=*)
             _root=$(RetrieveDriveValue "${param}")
             ;;
+        resume=*)
+            _resume=$(RetrieveDriveValue "${param}")
+            ;;
         options=*)
             _options=$(ParseOption "${param}")
             ;;
@@ -289,7 +293,7 @@ GetDrivesNeededToDecrypt()
     fi
 
     IFS="," read -a tempDrives <<< "${_enc_drives}"
-    
+
     for i in "${!tempDrives[@]}"; do
         case ${tempDrives[i]} in
             UUID=*)
@@ -534,16 +538,16 @@ DecryptDrives()
 
     if [[ ! -z ${_enc_targets// } ]]; then
         IFS="," read -a tempTargets <<< "${_enc_targets}"
-    fi 
+    fi
 
     for i in "${!_drives[@]}"; do
-    
+
         if [[ -z ${tempTargets[i]// } ]]; then
             vaultname=vault_${i}
         else
             vaultname=${tempTargets[i]}
         fi
-            
+
         if [[ ${_enc_type} == "pass" ]]; then
             while [[ ${count} -lt ${max} ]]; do
                 # Putting the _enc_options var in double quotes _will_ cause cryptsetup to fail
@@ -597,7 +601,7 @@ DecryptDrives()
             done
         fi
     done
-    
+
     unset tempTargets
 }
 
@@ -754,6 +758,20 @@ MountUsrIfNeeded()
     fi
 }
 
+# Resume after hibernation
+Resume()
+{
+    if [[ -z ${_resume} ]]; then
+        return 0
+    fi
+
+    Info "Detected resume device ${_resume}"
+
+    local device=$(ls -lL "${_resume}" | sed 's/\  */ /g' | cut -d \  -f 5-6 | sed 's/,\ */:/')
+
+    [ -f /sys/power/resume -a -n "${device}" ] && echo "${device}" > /sys/power/resume
+}
+
 # Switches into your root device
 SwitchToNewRoot()
 {
@@ -887,6 +905,8 @@ MountUsrIfNeeded
 
 [[ ${_su} -eq 1 ]] && SingleUser
 
+Resume
+
 # Clean up and switch into rootfs
 StopUdev
 UnmountRequiredDevices || Fail "Failed to unmount kernel devices"
`

**Comment by rocky-hxh** [comment]
```shell
diff --git a/files/init b/files/init
index 6751fc1..d682a7a 100755
--- a/files/init
+++ b/files/init
@@ -26,6 +26,7 @@ _use_addon=0
 
 _new_root="/mnt/root"
 _init="/sbin/init"
+_resume="dev/mapper/swap"
 _key_drive="/mnt/key"
 _embedded_keyfile="/etc/keyfile"
 _cache_file="/etc/zfs/zpool.cache"
@@ -139,6 +140,9 @@ ParseKernelParameters()
         root=*)
             _root=$(RetrieveDriveValue "${param}")
             ;;
+        resume=*)
+            _resume=$(RetrieveDriveValue "${param}")
+            ;;
         options=*)
             _options=$(ParseOption "${param}")
             ;;
@@ -289,7 +293,7 @@ GetDrivesNeededToDecrypt()
     fi
 
     IFS="," read -a tempDrives <<< "${_enc_drives}"
-    
+
     for i in "${!tempDrives[@]}"; do
         case ${tempDrives[i]} in
             UUID=*)
@@ -534,16 +538,16 @@ DecryptDrives()
 
     if [[ ! -z ${_enc_targets// } ]]; then
         IFS="," read -a tempTargets <<< "${_enc_targets}"
-    fi 
+    fi
 
     for i in "${!_drives[@]}"; do
-    
+
         if [[ -z ${tempTargets[i]// } ]]; then
             vaultname=vault_${i}
         else
             vaultname=${tempTargets[i]}
         fi
-            
+
         if [[ ${_enc_type} == "pass" ]]; then
             while [[ ${count} -lt ${max} ]]; do
                 # Putting the _enc_options var in double quotes _will_ cause cryptsetup to fail
@@ -597,7 +601,7 @@ DecryptDrives()
             done
         fi
     done
-    
+
     unset tempTargets
 }
 
@@ -754,6 +758,20 @@ MountUsrIfNeeded()
     fi
 }
 
+# Resume after hibernation
+Resume()
+{
+    if [[ -z ${_resume} ]]; then
+        return 0
+    fi
+
+    Info "Detected resume device ${_resume}"
+
+    local device=$(ls -lL "${_resume}" | sed 's/\  */ /g' | cut -d \  -f 5-6 | sed 's/,\ */:/')
+
+    [ -f /sys/power/resume -a -n "${device}" ] && echo "${device}" > /sys/power/resume
+}
+
 # Switches into your root device
 SwitchToNewRoot()
 {
@@ -887,6 +905,8 @@ MountUsrIfNeeded
 
 [[ ${_su} -eq 1 ]] && SingleUser
 
+Resume
+
 # Clean up and switch into rootfs
 StopUdev
 UnmountRequiredDevices || Fail "Failed to unmount kernel devices"
```

**Comment by fearedbliss** [comment]
Hey, as stated in the front page of the project:

"This project is no longer in development. Please fork. Thank you."
