### ISSUE TITLE
Boot failure on mount with kernel 5.10. / older bliss versions

### ISSUE THREAD

**Issue by ste7677** [fearedbliss/bliss-initramfs#35]
Please apologize the long text, this is issue is quite hard to explain.

What I did: 

- Full gentoo update including zfs drivers
- Kernel update 
- NO zpool upgrades

After upgrading my kernel from 4.x to 5.10.11, the machine won't boot anymore. It goes into the initrd's rescue shell reporting the error (screenshot image attached):

mount: mounting ZFS/rpool/gentoo on /mnt/root failed: No such file or directory

Some facts:
- building initrd with bliss-initramfs worked without any errors (any version)
- when in initrd, issuing "zpool import rpool" works without errors, not even "-f" needed
- booting the machine with the older 4.20 kernel still works without errors
- booting initrd with bliss-initramfs 8.1.0 fails too
- booting initrd with bliss-initramfs 9.3.0 WORKS but is not an option due to missing LUKS support
- tried different kernel APPEND options already (root=ZFS=rpool/gentoo, root=rpool/gentoo, dozfs=force etc) - no success

Now my question is:

What would be the actual source / reason for the error above? I'm completely stuck, working since days on that.

I'm happy to provide more information.

Attachements:
- kernel .config
- error screenshot

![error-initramfs](https://user-images.githubusercontent.com/19426959/106595315-ad5a4f80-6553-11eb-9224-d0dee6c4bb5e.jpg)

[5.10.11-kernel.config.txt](https://github.com/fearedbliss/bliss-initramfs/files/5910833/5.10.11-kernel.config.txt)

**Comment by fearedbliss** [comment]
Responded in issue #34.
