### ISSUE TITLE
Running bliss-initramfs fails with 'busybox: ... : Operation not permitted'

### ISSUE THREAD

**Issue by sancoder** [fearedbliss/bliss-initramfs#36]
Trying to follow the guide at https://wiki.gentoo.org/wiki/User:Fearedbliss/Installing_Gentoo_Linux_On_ZFS

Had to install busybox with `emerge busybox`.

While executing bliss-initramfs got the following output.
```
------------------------------
Bliss Initramfs - v9.3.0
Jonathan Vasquez <jon@xyinn.org>
Apache License 2.0
------------------------------

[*] Checking preliminary binaries ...
[*] Creating temporary directory at /boot/bi-395389259 ...
[*] Checking required files ...
[*] Copying binaries ...
[!] Unable to copy /bin/zgenhostid
[*] Copying modules ...
[+] Module: zfs
[*] Generating modprobe information ...
[*] Copying library dependencies ...
[*] Creating symlinks ...
busybox: ./[: Operation not permitted
busybox: ./[[: Operation not permitted
busybox: ./acpid: Operation not permitted
busybox: ./addgroup: Operation not permitted
...
busybox: ./zcat: Operation not permitted
busybox: ./zcip: Operation not permitted
Traceback (most recent call last):
  File "/sbin/bliss-initramfs", line 57, in <module>
    Main.start()
  File "/sbin/bliss-initramfs", line 50, in start
    Core.CreateLinks()
  File "/opt/bliss-initramfs/pkg/libs/Core.py", line 269, in CreateLinks
    os.remove(var.temp + "/bin/sh")
FileNotFoundError: [Errno 2] No such file or directory: '/boot/bi-395389259/bin/sh'
```

**Comment by sancoder** [comment]
After some time of digging into this issue, I realized that the command bliss-initramfs must be run when current directory filesystem is zfs. If my filesystem is fat the tool fails.
In the code, `home = os.getcwd()` in pkg/libs/Variables.py defines a folder where the things will be packed. Packing is done via making bunch of symlinks. And if current directory filesystem (FAT in my case) does not support symlinks, the tool fails.

**Comment by fearedbliss** [comment]
That's correct and it is expected behavior given that this is a tool for a UNIX system using UNIX filesystem attributes. The tool can/should work on any native UNIX filesystems (like ext4, zfs, etc). FAT is really only used for the UEFI partition and thus bliss-initramfs needs to be ran outside of that partition given the FAT limitation.

For the record, I don't develop this tool anymore and I switched to FreeBSD many years ago.
